apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - us-east-1b
  containers:
  - name: ubuntu
    command: ['tail', '-f', '/dev/null']
    image: ubuntu:18.04
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    awsElasticBlockStore:
      volumeID: vol-043b6c84ba7206a9f
      fsType: ext4
