apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: example-{{ .Release.Name }}
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ['--cpu', '1']
    resources:
      requests:
        cpu: 250m
      limits:
        cpu: 500m
