apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: example-{{ .Release.Name }}
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ['--vm', '1', '--vm-bytes', '200M']
    resources:
      requests:
        memory: 50M
      limits:
        memory: 100M

