apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: example-{{ .Release.Name }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}  
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        command: ['bogus']
      restartPolicy: Never

