apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: ubuntu
    command: ['tail', '-f', '/dev/null']
    image: ubuntu:18.04
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
