apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: none-{{ .Release.Name }}
spec:
  hard:
    requests.cpu: "300m"
    limits.cpu: "450m"

