apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: ubuntu
    command: ['tail', '-f', '/dev/null']
    image: ubuntu:18.04
    volumeMounts:
    - name: data
      mountPath: /data
  nodeSelector:
    topology.ebs.csi.aws.com/zone: us-east-1b
  volumes:
  - name: data
    awsElasticBlockStore:
      volumeID: vol-043b6c84ba7206a9f
      fsType: ext4
