apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: httpd-{{ .Release.Name }}
spec:
  selector:
    example: httpd
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
