apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: nginx-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      example: nginx
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}  
        example: nginx
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: http
        image: nginx:1.17.10
        ports:
        - containerPort: 80
