apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: b-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      example: b
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}  
        example: b
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: http
        image: httpd:2.4.43
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index
          mountPath: /usr/local/apache2/htdocs/b
      volumes:
      - name: index
        configMap:
          name: b-{{ .Release.Name }}

