apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: example-{{ .Release.Name }}
spec:
  rules:
  - http:
      paths:
      - path: /a/*
        backend:
          serviceName: a-{{ .Release.Name }}
          servicePort: 80
      - path: /b/*
        backend:
          serviceName: b-{{ .Release.Name }}
          servicePort: 80

