apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: example-{{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}  
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: http
        image: nginx:1.17.10
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: ssl
        - mountPath: /etc/nginx/conf.d
          name: conf-d
      volumes:
      - name: ssl
        secret:
          secretName: example-{{ .Release.Name }}
      - name: conf-d
        configMap:
          name: example-{{ .Release.Name }}
