apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: example-{{ .Release.Name }}
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ['tail', '-f', '/dev/null']
    volumeMounts:
    - mountPath: /cert
      name: ca-crt
  volumes:
  - name: ca-crt
    configMap:
      name: ca