apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: any-from-any-none-{{ .Release.Name }}
  namespace: production-{{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress

