apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: data-from-logic-redis-{{ .Release.Name }}
  namespace: production-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      networking/data: "true"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          networking/logic: "true"
    ports:
    - protocol: TCP
      port: 6379

