apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: logic-from-any-http-{{ .Release.Name }}
  namespace: production-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      networking/logic: "true"
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80

