apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    network/production-{{ .Release.Name }}: "true"
  name: production-{{ .Release.Name }}
