apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: redis-{{ .Release.Name }}
  namespace: production-{{ .Release.Name }}
spec:
  selector:
    app: redis
    release: {{ .Release.Name }}
  ports:
    - name: redis
      protocol: TCP
      port: 6379
