apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    networking/logic: "true"
  name: ubuntu-{{ .Release.Name }}
  namespace: production-{{ .Release.Name }}
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ['tail', '-f', '/dev/null']

