apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: unprivileged-{{ .Release.Name }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: 
    - unprivileged-{{ .Release.Name}}
  verbs: ["use"]

