apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fruit:edit
  namespace: a
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["fruit"]
  verbs: ["get", "patch", "update"]

