apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fruit:edit
  namespace: a
subjects:
- kind: User
  name: suzi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fruit:edit
  apiGroup: rbac.authorization.k8s.io
