apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: guaranteed-{{ .Release.Name }}
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ['tail', '-f', '/dev/null']
    resources:
      requests:
        cpu: 250m
        memory: 10M
      limits:
        cpu: 250m
        memory: 10M
