apiVersion: v1
kind: LimitRange
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: example-{{ .Release.Name }}
spec:
  limits:
  - max:
      cpu: 200m
    min:
      cpu: 50m
    type: Container
