apiVersion: apps/v1 
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: headless-{{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      example: headless
      release: {{ .Release.Name }}
  serviceName: headless-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}  
        example: headless
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: http
        image: httpd:2.4.43
        ports:
        - containerPort: 80
