apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: headless-{{ .Release.Name }}
spec:
  selector:
    example: headless
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
  clusterIP: None
