apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    example: pod
    release: {{ .Release.Name }}
  name: pod-a-{{ .Release.Name }}
spec:
  hostname: pod-a
  subdomain: pod-{{ .Release.Name }}
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ['tail', '-f', '/dev/null']
