apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: example-{{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        command: ['tail', '-f', '/dev/null']

