apiVersion: v1 
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
    release: dev
  name: example-{{ .Release.Name }}
  namespace: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ['tail', '-f', '/dev/null']

